[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
monitor_speed = 115200
lib_deps = mincrmatt12/STM32Cube Middleware-FreeRTOS
custom_freertos_config_location = include/FreeRTOSConfig.h